name = "apollo-auto-punch"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[[kv_namespaces]]
binding = "STATE"
id = "REPLACE_WITH_KV_ID"

[vars]
TIMEZONE = "Asia/Taipei"
PUNCH_LATITUDE = "25.0781415"
PUNCH_LONGITUDE = "121.5703676"
USER_AGENT = "Apollo HR XE/3.0.41 (iPhone; iOS 13.3; Scale/2.00)"
DRY_RUN = "true"
